-- AlterTable
ALTER TABLE "campaigns" ADD COLUMN     "current_step" INTEGER NOT NULL DEFAULT 1,
ALTER COLUMN "cpm" DROP NOT NULL,
ALTER COLUMN "min_views" DROP NOT NULL,
ALTER COLUMN "max_views" DROP NOT NULL,
ALTER COLUMN "budget" DROP NOT NULL,
ALTER COLUMN "start_date" DROP NOT NULL,
ALTER COLUMN "end_date" DROP NOT NULL;
